apiVersion: v1
kind: Service
metadata:
  name: menufrontend
spec:
  type: NodePort
  selector:
    app: menufrontend
  ports:
    - protocol: TCP
      nodePort: 30090
      port: 3000
      targetPort: 3000